### PR TITLE
add Namufix Setting index (after login "https://namu.wiki/mypage")

### PR DESCRIPTION
**Pull request by Nekopoly**
사이트 레이아웃 div에 나무픽스 설정 메뉴 생성(로그인시 mypage)

### CODE REVIEW

**Comment by LiteHell** [comment]
Please fix these problems.
* Broken Korean on CSS file
* Use escape seqeunce if you have to type **"** in literal string

**Comment by LiteHell** [comment]
also, floating button can make users inconvenient, think deeper.

**Comment by LiteHell** [comment]
I said **Esacpe Sequence**, not Removing **"**

**Comment by Nekopoly** [comment]
제대로 했음

**Comment by LiteHell** [comment]
Good, code has no grammatical problem. I'll debug it soon. please wait until debugging finished.

**Pull request closed without merging**
